package com.astral.qatotoalpha.util.repository

import com.astral.qatotoalpha.R
import com.astral.qatotoalpha.util.model.AnimeModel

class AnimeRepository {
    fun getAllData() = listOf(
        AnimeModel(
            videoId = "4",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_5,
            videoTitle = "Anime 5",
            recentEpisodeRank = 5,
            recommendedForYouRank = 5,
            completedSeriesRank = 5,
            trendingRank = 5,
            newArrivalRank = 5,
            isLive = false,
            profileImage = R.drawable.profile_image_1,
            channelName = "Anime Channel 5",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "2",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_2,
            videoTitle = "Anime 2",
            recentEpisodeRank = 2,
            recommendedForYouRank = 2,
            completedSeriesRank = 2,
            trendingRank = 2,
            newArrivalRank = 2,
            isLive = false,
            profileImage = R.drawable.profile_image_2,
            channelName = "Anime Channel 2",
            videoViews = "1.1M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=2"
        ),
        AnimeModel(
            videoId = "1",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_3,
            videoTitle = "Anime 3",
            recentEpisodeRank = 3,
            recommendedForYouRank = 3,
            completedSeriesRank = 3,
            trendingRank = 3,
            newArrivalRank = 3,
            isLive = false,
            profileImage = R.drawable.profile_image_3,
            channelName = "Anime Channel 3",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "5",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_4,
            videoTitle = "Anime 4",
            recentEpisodeRank = 4,
            recommendedForYouRank = 4,
            completedSeriesRank = 4,
            trendingRank = 4,
            newArrivalRank = 4,
            isLive = false,
            profileImage = R.drawable.profile_image_4,
            channelName = "Anime Channel 3",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "6",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_6,
            videoTitle = "Anime 6",
            recentEpisodeRank = 6,
            recommendedForYouRank = 6,
            completedSeriesRank = 6,
            trendingRank = 6,
            newArrivalRank = 6,
            isLive = false,
            profileImage = R.drawable.profile_image_2,
            channelName = "Anime Channel 6",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "7",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_7,
            videoTitle = "Anime 7",
            recentEpisodeRank = 7,
            recommendedForYouRank = 1,
            completedSeriesRank = 7,
            trendingRank = 7,
            newArrivalRank = 7,
            isLive = false,
            profileImage = R.drawable.profile_image_3,
            channelName = "Anime Channel 7",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "8",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_8,
            videoTitle = "Anime 8",
            recentEpisodeRank = 8,
            recommendedForYouRank = 2,
            completedSeriesRank = 8,
            trendingRank = 8,
            newArrivalRank = 8,
            isLive = false,
            profileImage = R.drawable.profile_image_4,
            channelName = "Anime Channel 8",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "3",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_1,
            videoTitle = "God Troubles Me Season 3",
            recentEpisodeRank = 1,
            recommendedForYouRank = 1,
            completedSeriesRank = 1,
            trendingRank = 1,
            newArrivalRank = 1,
            isLive = true,
            profileImage = R.drawable.profile_image_1,
            channelName = "Anime Channel 1",
            videoViews = "1.2M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=1"
        ),
        AnimeModel(
            videoId = "9",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_9,
            videoTitle = "Anime 9",
            recentEpisodeRank = 9,
            recommendedForYouRank = 3,
            completedSeriesRank = 9,
            trendingRank = 9,
            newArrivalRank = 9,
            isLive = false,
            profileImage = R.drawable.profile_image_1,
            channelName = "Anime Channel 9",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "10",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_10,
            videoTitle = "Anime 10",
            recentEpisodeRank = 10,
            recommendedForYouRank = 4,
            completedSeriesRank = 10,
            trendingRank = 10,
            newArrivalRank = 10,
            isLive = false,
            profileImage = R.drawable.profile_image_2,
            channelName = "Anime Channel 10",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "11",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_11,
            videoTitle = "Anime 11",
            recentEpisodeRank = 11,
            recommendedForYouRank = 5,
            completedSeriesRank = 11,
            trendingRank = 11,
            newArrivalRank = 11,
            isLive = false,
            profileImage = R.drawable.profile_image_3,
            channelName = "Anime Channel 11",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        ),
        AnimeModel(
            videoId = "12",
            videoThumbnail = R.drawable.anime_landscape_thumbnail_12,
            videoTitle = "Anime 12",
            recentEpisodeRank = 12,
            recommendedForYouRank = 6,
            completedSeriesRank = 12,
            trendingRank = 12,
            newArrivalRank = 12,
            isLive = false,
            profileImage = R.drawable.profile_image_4,
            channelName = "Anime Channel 12",
            videoViews = "1.0M",
            videoLength = "24:00",
            videoUrl = "https://www.youtube.com/watch?v=3"
        )
    )
}